- name: INstall Nginx
  hosts: WEB
  become: true
  tasks:
    - name: Installl nginx
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: start nginx
      ansible.builtin.systemd:
        name: nginx
        state: started